[package]
categories = ["cryptography"]
description = "Parses and validates AWS Nitro Enclave attestation documents"
edition = "2024"
keywords = ["nitro", "attestation", "zkvm"]
license = "UNLICENSED"
name = "nitro-attestation"
readme = "../README.md"
repository = "https://github.com/tahardi/bearclave-zkvm"
version = "0.1.0"

[dependencies]
ciborium = "0.2.2"
coset = "0.4.2"
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
thiserror = "2"

[dev-dependencies]
base64 = "0.22.1"
hex = "0.4.3"
