[workspace]
resolver = "3"
members = ["nitro-attestation", "methods", "host"]

[workspace.dependencies]
risc0-build = { version = "=3.0.5" }
risc0-zkvm = { version = "=3.0.5" }

[workspace.package]
edition = "2024"

[profile.bench]

[profile.dev]
debug = true
incremental = true
opt-level = 3
overflow-checks = true
panic = "unwind"

[profile.release]
debug = false
incremental = false
lto = true
opt-level = 3

[profile.test]
